name: exception-context-th
version: '0.0.1'
synopsis: Add context to exception
description: Template Haskell macroses that add location info to exception
category: Error Handling
author: Aleksey Makarov
maintainer: aleksey.makarov@gmail.com
copyright: Aleksey Makarov
license: BSD3
homepage: https://github.com/aleksey-makarov/exception-context-th
dependencies:
  - base >=4.6 && <5.0
tested-with: GHC == 8.10.7
ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wno-redundant-constraints
extra-doc-files:
    - ChangeLog.md
    - README.md

github: aleksey-makarov/exception-context-th

library:
  dependencies:
    - template-haskell >= 2.15 && < 2.19
    - exceptions
  source-dirs: src
  exposed-modules:
    - Control.Exception.ContextTH

tests:
  exceptions:
    main: Test.hs
    source-dirs: tests
    dependencies:
      - exceptions
      - tasty
      - tasty-hunit
      - exception-context-th
